name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install deps
      run: npm ci
    - name: build spec
      run: npm run spec
    - name: build polyfill
      run: npm run build
    - name: test polyfill
      run: npm test
